export const CURRENT_USER = "CURRENT_USER";

export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";

export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_CANDIDATES = "GET_CANDIDATES";
export const GET_VICE_CANDIDATES = "GET_VICE_CANDIDATES";
export const VOTE_FOR_CANDIDATE = "VOTE_FOR_CANDIDATE";
export const VOTE_FOR_VICE_CANDIDATE = "VOTE_DEPUTY_CANDIDATE";
export const EDIT_USER = "EDIT_USER";
export const GET_USER = "GET_USER";
export const ADD_DEADLINE = "ADD_DEADLINE";
export const SEARCHED_USERS = "SEARCHED_USERS";

